export function drawPlayerBullet(context: CanvasRenderingContext2D) {
  context.beginPath();
  context.arc(+0, +0, 10, Math.PI, Math.PI * 2);
  context.moveTo(+0 + 10, +0);
  context.bezierCurveTo(+0 + 11, +1, +6, +17, +6, +22);
  context.quadraticCurveTo(+0, +36, -6, +22);
  context.bezierCurveTo(-6, +17, -11, +1, -10, +0);
  context.closePath();
  context.fillStyle = "#000099";
  context.fill();
  context.beginPath();
  context.arc(+0, -2, 8, Math.PI, Math.PI * 2);
  context.moveTo(+8, -2);
  context.bezierCurveTo(+10, +1, +6, +11, +2, +15);
  context.quadraticCurveTo(+0, +27, -2, +15);
  context.bezierCurveTo(-6, +11, -10, +1, -8, -2);
  context.closePath();
  context.fillStyle = "#0000FF";
  context.fill();
  context.beginPath();
  context.arc(+0, -3, 6, Math.PI, Math.PI * 2);
  context.moveTo(+6, -3);
  context.bezierCurveTo(+8, +0, +4, +4, +1, +10);
  context.quadraticCurveTo(+0, +18, -1, +10);
  context.bezierCurveTo(-4, +4, -8, +0, -6, -3);
  context.closePath();
  context.fillStyle = "#0099FF";
  context.fill();
  context.beginPath();
  context.arc(+0, -4, 4, Math.PI, Math.PI * 2);
  context.moveTo(+4, -4);
  context.quadraticCurveTo(+0, +14, -4, -4);
  context.closePath();
  context.fillStyle = "#00FFFF";
  context.fill();
}
