export function drawPlayerShip(context: CanvasRenderingContext2D) {
  context.beginPath();
  context.moveTo(+4, +14);
  context.quadraticCurveTo(+8, -14, +13, +14);
  context.quadraticCurveTo(+8, +14, +4, +14);
  context.quadraticCurveTo(+8, +16, +13, +14);
  context.fillStyle = "#FFFFFF";
  context.fill();
  context.strokeStyle = "#000000";
  context.stroke();
  context.beginPath();
  context.moveTo(-4, +14);
  context.quadraticCurveTo(-8, -14, -13, +14);
  context.quadraticCurveTo(-8, +14, -4, +14);
  context.quadraticCurveTo(-8, +16, -13, +14);
  context.fillStyle = "#FFFFFF";
  context.fill();
  context.strokeStyle = "#000000";
  context.stroke();
  context.beginPath();
  context.moveTo(+4, -1.2);
  context.lineTo(+10, -6);
  context.lineTo(+8, -14);
  context.lineTo(+10, -16);
  context.lineTo(+16, +2);
  context.lineTo(+0, +16);
  context.lineTo(-16, +2);
  context.lineTo(-10, -16);
  context.lineTo(-8, -14);
  context.lineTo(-10, -6);
  context.lineTo(-4, -1.2);
  context.quadraticCurveTo(+0, -24, +4, -1.2);
  context.closePath();
  context.fillStyle = "#FFFFFF";
  context.fill();
  context.strokeStyle = "#000000";
  context.stroke();
}
